version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save-cache:
          key: "npm-packages"
          path: 
            /src/node-modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore-cache:
          keys: 
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore-cache:
          keys: 
            - "npm-packages"
      - run: npm audit

workflows:
  my_workflows:
    - build
    - test:
        requires:
          - build
    - analyze:
        requires:
          - test